const pages = {
  sudoMode: "SUDO_MODE",
  home: "HOME",
  catagories: "CATAGORIES",
  myAccount: "MY_ACCOUNT",
  cart: "CART",
  productDetails: "PRODUCT_DETAILS",
  app: "APP",
  product: "PRODUCT",
  images: "IMAGES",
  details: "DETAILS",
  reviews: "REVIEWS",
  newReview: "NEW_REVIEW",
  mainCategories: "MAIN_CATEGORIES",
  search: "SEARCH",
  subCategories: "SUB_CATEGORIES",
  specialOffers: "SPECIAL_OFFERS",
  settings: "SETTINGS",
  addresses: "ADDRESSES",
  addAddress: "ADD_ADDRESS",
  editAddress: "EDIT_ADDRESS",
  persoanlInfo: "PERSONAL_INFO",
  selectShippingMethos: "SELECT_SHIPPING_METHODS",
  resetPassword: "RESET_PASSWORD",
  messages: "MESSAGES",
  orderDetail: "ORDER_DETAIL",
  invoice: "INVOICE",
  orderRegistered: "ORDER_REGISTERED",
  cutomerReviews: "CUSTOMER_REVIEWS",
  contactUs: "Contact_US",
  translator : "TRANSLATOR",
  orderHistory: "ORDER_HISTORY",
  privacy : "PRIVACY",
  termOfUse : "TERM_OF_USE"
};
export default pages;
